//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public Caja()
        {
            this.OrdenesPagoDetalles = new HashSet<OrdenesPagoDetalle>();
        }
    
        public System.Guid Id { get; set; }
        public int SucursalId { get; set; }
        public Nullable<System.Guid> OperadorId { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FCierre { get; set; }
        public Nullable<decimal> Inicio { get; set; }
        public Nullable<decimal> Ingresos { get; set; }
        public Nullable<decimal> Egresos { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> Cheques { get; set; }
        public Nullable<decimal> Bonos { get; set; }
        public string PcAlta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual Operadore Operadore { get; set; }
        public virtual Operadore Operadore1 { get; set; }
        public virtual Operadore Operadore2 { get; set; }
        public virtual Sucursale Sucursale { get; set; }
        public virtual Sucursale Sucursale1 { get; set; }
        public virtual Sucursale Sucursale2 { get; set; }
        public virtual ICollection<OrdenesPagoDetalle> OrdenesPagoDetalles { get; set; }
    }
}
