//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalNovedade
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonalId { get; set; }
        public int TipoNovedad { get; set; }
        public int ConceptoId { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int MesImputacion { get; set; }
        public int AnioImputacion { get; set; }
        public float Importe { get; set; }
        public Nullable<float> Total { get; set; }
        public Nullable<System.Guid> LiquidacionPersonalId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
    
        public virtual Concepto Concepto { get; set; }
        public virtual Operadore Operadore { get; set; }
        public virtual Operadore Operadore1 { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Sucursale Sucursale { get; set; }
        public virtual Sucursale Sucursale1 { get; set; }
    }
}
