//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedore
    {
        public Proveedore()
        {
            this.OrdenesPagoes = new HashSet<OrdenesPago>();
            this.ProveedoresBancoes = new HashSet<ProveedoresBanco>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> Cuenta { get; set; }
        public string Denominacion { get; set; }
        public string Domicilio { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Fax { get; set; }
        public string Contacto { get; set; }
        public string Cuit { get; set; }
        public Nullable<int> TipoDocumento { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
        public Nullable<int> LocalidadId { get; set; }
        public Nullable<int> CondicionCompraId { get; set; }
        public Nullable<decimal> PorcentajeDescuento { get; set; }
        public string Password { get; set; }
        public Nullable<int> ProveerdorBcoId { get; set; }
        public string CBU { get; set; }
        public Nullable<int> GrupoProveedorId { get; set; }
        public string PaginaWeb { get; set; }
        public string EmailPedido { get; set; }
        public Nullable<int> Estado { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> Gto { get; set; }
        public bool Activo { get; set; }
        public int SucursalAltaId { get; set; }
        public System.DateTime FechaAlta { get; set; }
        public System.Guid OperadorAltaId { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public string PersonaContacto { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual CondicionesCompra CondicionesCompra { get; set; }
        public virtual GruposProveedore GruposProveedore { get; set; }
        public virtual Localidade Localidade { get; set; }
        public virtual Operadore Operadore { get; set; }
        public virtual Operadore Operadore1 { get; set; }
        public virtual ICollection<OrdenesPago> OrdenesPagoes { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual Sucursale Sucursale { get; set; }
        public virtual Sucursale Sucursale1 { get; set; }
        public virtual TiposDocumentosIdentidad TiposDocumentosIdentidad { get; set; }
        public virtual ICollection<ProveedoresBanco> ProveedoresBancoes { get; set; }
    }
}
