//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using GestionAdministrativa.Entities;
    
    public partial class GestionAdministrativaDbContext : DbContext
    {
        public GestionAdministrativaDbContext()
            : base("name=GestionAdministrativaDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<Cajas> Cajas { get; set; }
        public virtual DbSet<CajasMovimientos> CajasMovimientos { get; set; }
        public virtual DbSet<CategoriasOperadores> CategoriasOperadores { get; set; }
        public virtual DbSet<Celulares> Celulares { get; set; }
        public virtual DbSet<CelularesMovimiento> CelularesMovimiento { get; set; }
        public virtual DbSet<CentrosCostos> CentrosCostos { get; set; }
        public virtual DbSet<Choferes> Choferes { get; set; }
        public virtual DbSet<ChoferesMontosFavor> ChoferesMontosFavor { get; set; }
        public virtual DbSet<Conceptos> Conceptos { get; set; }
        public virtual DbSet<CondicionesCompra> CondicionesCompra { get; set; }
        public virtual DbSet<Dias> Dias { get; set; }
        public virtual DbSet<Funciones> Funciones { get; set; }
        public virtual DbSet<GruposProveedores> GruposProveedores { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Moviles> Moviles { get; set; }
        public virtual DbSet<Operadores> Operadores { get; set; }
        public virtual DbSet<OperadoresFunciones> OperadoresFunciones { get; set; }
        public virtual DbSet<OperadoresSucursales> OperadoresSucursales { get; set; }
        public virtual DbSet<OrdenesPago> OrdenesPago { get; set; }
        public virtual DbSet<OrdenesPagoDetalle> OrdenesPagoDetalle { get; set; }
        public virtual DbSet<PagosCelular> PagosCelular { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<PersonalConcepto> PersonalConcepto { get; set; }
        public virtual DbSet<PersonalNovedades> PersonalNovedades { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<ProveedoresBanco> ProveedoresBanco { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Recibos> Recibos { get; set; }
        public virtual DbSet<RecibosDetalle> RecibosDetalle { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sucursales> Sucursales { get; set; }
        public virtual DbSet<TiposCelulares> TiposCelulares { get; set; }
        public virtual DbSet<TiposComprobantes> TiposComprobantes { get; set; }
        public virtual DbSet<TiposDocumentosIdentidad> TiposDocumentosIdentidad { get; set; }
        public virtual DbSet<TiposGastos> TiposGastos { get; set; }
        public virtual DbSet<TiposMovimientosCajas> TiposMovimientosCajas { get; set; }
        public virtual DbSet<TiposRecibos> TiposRecibos { get; set; }
    }
}
