//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionAdministrativa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celulares
    {
        public Celulares()
        {
            this.CelularesMovimiento = new HashSet<CelularesMovimiento>();
            this.PagosCelular = new HashSet<PagosCelular>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> TipoCelularId { get; set; }
        public Nullable<System.DateTime> Alta { get; set; }
        public Nullable<System.DateTime> Baja { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Pagare { get; set; }
        public Nullable<bool> Habilitado { get; set; }
        public Nullable<System.DateTime> FechaUltimoPago { get; set; }
        public Nullable<System.DateTime> FechaProximoPago { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> DiaPagoId { get; set; }
        public Nullable<System.DateTime> FechaVencimientoPago { get; set; }
        public Nullable<System.Guid> OperadorAltaId { get; set; }
        public Nullable<int> SucursalAltaId { get; set; }
        public Nullable<System.Guid> OperadorModificacionId { get; set; }
        public Nullable<int> SucursalModificacionId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Dias Dias { get; set; }
        public virtual Operadores Operadores { get; set; }
        public virtual Operadores Operadores1 { get; set; }
        public virtual Sucursales Sucursales { get; set; }
        public virtual Sucursales Sucursales1 { get; set; }
        public virtual TiposCelulares TiposCelulares { get; set; }
        public virtual ICollection<CelularesMovimiento> CelularesMovimiento { get; set; }
        public virtual ICollection<PagosCelular> PagosCelular { get; set; }
    }
}
